### ISSUE TITLE
Cannot open database export

### ISSUE THREAD

**Issue by puresick** [nickv-nextcloud/gadgetbridge#1]
### Steps to reproduce
1. Export Gadgetbridge DB
2. Upload to Nextcloud Instance
3. Open it in the Nexcloud Gadgetbridge app

### Expected behaviour
Gadgetbridge DB should be read and visualized

### Actual behaviour
Error message: `The selected file is not a readable Gadgetbridge database`

### Server configuration
**Operating system**:
Debian 9.3

**Web server:**
nginx 1.10.3

**Database:**
MariaDB

**PHP version:**
7.0.27

**Nextcloud version:** (see Nextcloud admin page)
13.0

**Where did you install Nextcloud from:**
Manually from Github

**List of activated apps:**

```
Enabled:
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.0
  - contacts: 2.1.0
  - dav: 1.4.6
  - deck: 0.3.0
  - encryption: 2.0.0
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - gadgetbridge: 0.5.5
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - news: 12.0.1
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - activity
  - admin_audit
  - comments
  - federation
  - files_external
  - firstrunwizard
  - notifications
  - sharebymail
  - spreed
  - survey_client
  - systemtags
  - tasks
  - user_external
  - user_ldap
```

### Client configuration
**Browser:**
Most recent Chromium, Firefox and qutebrowser

**Operating system:**
Arch Linux (most recent)

**GadgetBridge Version Android**
Version 0.24.5

**Comment by nickvergessen** [comment]
Which device are you using?

At the moment it only works with the MiBand 2.
The idea was to have the data available in device-independent format.
Sofar this seems to not be the case, which means we have to take care of all the action types for all apps, similar to the android app, which is quite a huge pain.

**Comment by puresick** [comment]
Ah, good to know!
I'm trying to use it with a Pebble 2 HR.

**Comment by nickvergessen** [comment]
PS: if you are willing to share your data for testing, you can send me an email to https://github.com/nickv-nextcloud/gadgetbridge/blob/master/appinfo/app.php#L3

Otherwise you will have to wait until either the data is independent of the device, or something else happened.

**Comment by puresick** [comment]
Hey sure, I'll send you an email!

**Comment by ghost** [comment]
I encounter the same issue here, i.e. i get "The selected file is not a readable Gadgetbridge database" when i try to open a Gadgetbridge database export but i am using a Miband 2. 

Which Miband 2 firmware do you use? I checked with v0.1.3.2 and 0.1.3.9

Additional information: Nextcloud 13.0.1, Gadgetbridge 0.25

**Comment by nickvergessen** [comment]
I'm on 1.0.1.53

**Comment by ghost** [comment]
Flashed 1.0.1.53 but nothing changed. Are there any log files?

Flashed back to a recommended version 1.0.1.39. I will check at the weekend: backup of the DB, clean up and retest.

**Comment by ghost** [comment]
I emptied the Gadgetbridge database and recorded activity for about 5 minutes with and without continuous HR monitoring, no difference when loading the database "The selected file is not a readable Gadgetbridge database". 

I will send you a DB example.

**Comment by ghost** [comment]
@nickvergessen I flashed firmware 1.0.1.53 which you use, HW revision is v0.1.3.2, gadgetbridge v0.25, emptied my database and recorded some data, no change. Also checked that MI_BAND_ACTIVITY_DATA doesn't contain RAW_KIND = 0 or 1?!
